### ISSUE TITLE
Better way to detect errors from syscalls

### ISSUE THREAD

**Issue by Hermes1312** [zaneGittins/go-inject#2]
Hi,

I see u are checking if syscall functions return error by this statement `if err.Error() != inject.SUCCESS`, but there is better aproach instead u can check `if err != windows.Errno(0)` bcs err is type of {error | syscall.Errno} that means its error and syscall.Errno at the same time. 

Btw your method is not working if windows language is diffrent than ENG :)

**Comment by Hermes1312** [comment]
Also at line 76 in [apc queue injection ](https://github.com/zaneGittins/go-inject/blob/master/examples/x64/queue-user-apc/queue.go#L76)u can change `if err.Error() == inject.ERROR_NO_MORE_FILES` to `if err == windows.Errno(18)`.

According to ChatGPT:
> The error code for "There are no more files" in Windows is usually "ERROR_NO_MORE_FILES", which has a numerical value of 0x12 (18 in decimal) and is part of the Win32 error code system. This error message typically indicates that a program or process has attempted to access a file or directory that does not exist, has been deleted, or cannot be accessed for some other reason.

**Comment by zaneGittins** [comment]
Thanks for the insight! You make some good points. Pull requests are welcome

**Comment by zaneGittins** [comment]
Should be fixed in commit 91eb4e4db2c60568bd6da9ab6cd9fc7df1def44c
